### PR TITLE
Replace BioWardrobe-NG with NJS-Client

### PR DESCRIPTION
**Pull request by heylel-b-sh**
**Starting point**
Use CWL-Airflow 1.2.10 that reports statistics, use BioWardrobe-NG 2.0.2 that works with that version of CWL-Airflow. Bundle built for macOS should work, however it was never installed on any client's computers and might need more careful testing.

## Notes for developers
- LDAP authentication will be run not from the bundle itlsef, but from the modified version of BioWardrobe-NG as a standalone application.
- For the current NJS-Client implementation (a.k.a `scidap-satellite` from `scidapsatelliteinteractions` project) we need to set the path to the `settings.yaml` therefore it will be always created at the same folder from where the configuration was read. For macOS it's always alongside `config.json`, for Ubuntu it will depend on the actual location of configuration file. Later all these parameters would be nice to read directly from the environment variable the same way we used `METEOR_SETTINGS` for BioWardobe-NG.
- The following field won't be included into `scidap_default_settings.json` as it's currently not implemented in NJS-Client, however present in it's default settings example.
   ```json
    "privileges": {
        "read": "",
        "write": ""
    }
   ```
- In the current implementation of NJS-Client we can't restrict access to the local files on the satellite based on the specific settings parameter, therefore `localFiles` field from the `scidap_default_settings.json` will still present but not used.
- No need to have `scidapSSLPort`, `sslCert` and `sslKey` in the `scidap_default_settings.json`. Replace them with `enableSSL` as only `SSL_CONN=true` should be passed to NJS-Client to use SSL connection. Even port is the same as standard `port` parameter. All logic related to certificate management will be moved to the main server, so we don't need any buttons to attach certificates in this bundle.

## Check before merging this pull request

- [x] All Airflow configuration parameters are applied to the running Airflow through the environment variables.
- [ ] Check if really need to run `airflow` command without argument from `waitForInitConfiguration` function in order just to create `airflow.cfg`. If we make `cwl-airflow api` wait until `airflow scheduler` is started, we don't need `airflow.cfg` at all as it will be created for us automatically.
- [x] Update `rcServer` in the `scidap_default_settings.json` to point to the production server by default.
- [ ] Update NJS-Client version in the building script after `systemRoot/` bug is fixed. Remove correspondent patch from the `saveNjsClientSettings` function.
- [x] Make sure we don't use `NODE_ENV: 'development'` in `config.js`
- [x] Fix version for `NJS_CLIENT_VERSION` to something tested and stable
- [x] Make sure that `mac_update_from_devel` is set to False before merging

-----
> everything below this line will go to the README after merging
-----

# Building SciDAP-Satellite bundle for Ubuntu/CentOS and macOS

## Ubuntu/CentOS

**To build** relocatable `tar.gz` that can be run on Ubuntu 18.04/20.04, CentOS 7/8, follow these directions.
- Make sure that Docker is installed and properly configured [see installation instructions](https://docs.docker.com/engine/install/ubuntu/)
- Clone [scidap-satellite](https://github.com/datirium/scidap-satellite) repository and switch to the branch/tag/commit you want to build from. Note, all local changes in the `build-scripts` directory will be included in the bundle.
   ```bash
   git clone https://github.com/datirium/scidap-satellite
   cd scidap-satellite
   git checkout replaceBiowardrobeNG
   ```
- Set `BITBUCKET_USER` and `BITBUCKET_PASS` environment variables to pull NJS-Client from [scidapSatelliteInteractions](https://bitbucket.org/datirium/scidapsatelliteinteractions/commits). Note, we do not build from the local *scidapSatelliteInteractions* repository.
- Enter directory with the build scripts and run `build_linux_in_docker.sh`
   ```bash
   cd build-scripts
   ./build_linux_in_docker.sh
   ```
   > By default Ubuntu 18.04 will be used as a building environment. Alternatively, you can provide other docker images, such as `ubuntu:18.04`, `ubuntu:20.04`, `centos:7`, or `centos:8` in the first argument of the script.

After script finishes running, you will find a compressed `scidap-satellite-commitsha-ubuntu.tar.gz` in the `./bundle` folder. All the temporary data will be kept in `./build` and can be removed.

**To run** relocatable `tar.gz` on Ubuntu 18.04/20.04, CentOS 7/8, follow these directions.
- Make sure that Docker is installed and properly configured [see installation instructions](https://docs.docker.com/engine/install/ubuntu/)
- Uncompress `scidap-satellite-commitsha-ubuntu.tar.gz` into an empty folder and start `pm2` with `./configs/ecosystem.config.js` file. See how to provide custom settings location at the end of this section.
  ```bash
  mkdir satellite
  mv scidap-satellite-commitsha-ubuntu.tar.gz satellite                  # initial location of scidap-satellite.tar.gz might be different
  cd satellite
  tar xzf scidap-satellite-commitsha-ubuntu.tar.gz
  ./pm2 start ./configs/ecosystem.config.js
  ```
**To test** relocatable `tar.gz` on Ubuntu 18.04/20.04, CentOS 7/8, follow these directions.
- Enter directory with the build scripts and run `test_linux_bundle.sh` with the absolute path to the `scidap-satellite-commitsha-ubuntu.tar.gz` and Docker image to run tests in (`ubuntu:18.04`, `ubuntu:20.04`, `centos:7`, or `centos:8`)
   ```bash
   cd build-scripts
   ./test_linux_bundle.sh /absolute/path/scidap-satellite-commitsha-ubuntu.tar.gz ubuntu:20.04
   ```
After script finishes running, you will find all logs in the `./temp` folder. The exit code can be checked with `echo $?`

Default configuration is saved in the `./configs/scidap_default_settings.json` file. Custom configuration can be loaded from the file set in `SCIDAP_SETTINGS` environment variable, `../scidap_settings.json` or `~/.config/scidap-satellite/scidap_settings.json`.

### Troubleshooting
1. When running on CentOS Aria2c complains about certificates, update settings to include path to the certificate file
   ```
    "aria2cSettings": {
        "--ca-certificate": "/etc/ssl/certs/ca-bundle.crt"
    }
   ```
2. This shouldn't happen anymore, but If `libssl.so.1.0.0` and/or `libcrypto.so.1.0.0` are not found, **report a bug**, and then download them from the provided links below and save into the folder from the `defaultLocations.airflow` field of the the settings file. Update `getAirflowEnvVar(settings)` function from `./utilities/configure.js` file to include `LD_LIBRARY_PATH: settings.defaultLocations.airflow`.
   https://scidap.nyc3.digitaloceanspaces.com/centos/libcrypto.so.1.0.0
   https://scidap.nyc3.digitaloceanspaces.com/centos/libssl.so.1.0.0 

## macOS

**To build** Electron App on macOS follow these directions.
- Install required dependencies.
  ```bash
  brew install git
  brew install node@12
  npm install -g @nestjs/cli
  ```
- Clone `scidap-satellite` repository and switch to the `replaceBiowardrobeNG` branch. Install node modules.
   ```bash
   git clone https://github.com/datirium/scidap-satellite.git
   cd scidap-satellite && git checkout replaceBiowardrobeNG
   npm install
   ```
- Create a text file `.env` in the `./build-scripts` folder. Add there either `NJS_CLIENT_LOCAL_PATH` to build `scidapSatelliteInteractions` from the local repository, or a pair of `BITBUCKET_USER` and `BITBUCKET_PASS` variables to clone it from Bitbucket.  `NJS_CLIENT_LOCAL_PATH` should point to the `scidap-satellite` subdir as we don't need to build `apisync`. Optionally, the default programs versions used in the script can be redefined in `.env` file.
- Run `build_macos.sh` script inside the `./build-scripts` folder. Pack results into App. Use `electron:mac:prod` or `electron:mac:dev` depending on whether you want to connect to `https://api.scidap.com/` or `https://api-dev.scidap.com/`.
   ```bash
   cd ./build-scripts
   ./build_macos.sh
   cd ..
   npm run electron:mac:dev
   ```
After script finishes running, you will find a `scidap-satellite.app` in `./release/mac` folder. All the temporary data is kept in `../build` folder and can be removed unless you want to save some time when rerunning `build_macos.sh` script next time. When component versions are updated, remove `../build` folder. `Services` folder is used to save all necessary files before assembling application. This folder is cleaned on each `build_macos.sh` run.

**To run** Electron App on macOS with installed and configured Docker right-click on `scidap-satellite.app` and select `Open`.

In case you by mistake run `build_ubuntu.sh` script, you will need to remove `node_modules`, `build`, `build_ubuntu`, `Services`, `ubuntu_post_build` folders in the root of you repository and rerun `npm install`, `build_macos.sh` and `npm run electron:mac` commands as it's listed above.

The default configuration file from `./configs/scidap_default_settings.json` will be used by Electron for generating `config.json`.

## Default configuration

- `defaultLocations.airflow` and `defaultLocations.pgdata` define the locations for airflow configuration and PostreSQL database files correspondingly. If they are set as relative paths, they by default will be resolved based on the `satelliteSettings.systemRoot`. However, for macOS bundle if `satelliteSettings.systemRoot` was changed from the **Satellite data directory** parameter in the **Common** settings tab, the `defaultLocations.airflow` and `defaultLocations.pgdata` won't be re-evaluated.
- `satelliteSettings` section is mainly used by NJS-Client. On macOS `rcServerToken` shouldn't be set, as it will be read from Keychain. `systemRoot` defines the location where all analyses data will be saved. If it's set as a relative path, it will be resolved based on the user's home directory. The `remotes` section includes `localfiles` field with `show` set to `false` by default. This tells NJS-Client to disable access from UI to the local directories set as the `collection` items. If `show` set to `true` all relative `path` will be resolved based on the `satelliteSettings.systemRoot` value.
- all parameters from `airflowSettings` section will be applied to `airflow scheduler` and `cwl-airflow api`. It may include any valid parameter from `airflow.cfg` in a form of `"section__parameter": "value"`.
- all parameters from `aria2cSettings` section will be applied to `aria2c`. It may include any valid for Aria2c argument in a form of `"--flag": "value"`.
- `databaseSettings` section defines parameters for the running PostgreSQL database, that is always bound to `127.0.0.1` so it's safe keep default values unless additional security measures needed.
- `devel` section defines parameters used during developing. Currently, it includes only `simulation` and `mac_update_from_devel` parameters. The former allows to shortcut CWL-Airflow API without triggering any DAGs. The latter makes macOS build to check for the developers updates (different location on our DigitalOcean).

```yaml
{
    "defaultLocations": {
        "airflow": "airflow",
        "pgdata": "pgdata"
    },
    "satelliteSettings": {
        "rcServerToken": "",
        "rcServer": "dev.scidap.com:8080",
        "port": 3069,
        "airflowAPIPort": 8080,
        "systemRoot": "./scidap",
        "aria2cPort": 6800,
        "pm2Port": 9615,
        "enableSSL": true,
        "localFiles": true,
        "proxy": "",
        "noProxy": "",
        "remotes": {
            "directurl": {
                "protocol": [
                    "ftp",
                    "http",
                    "https"
                ],
                "caption": "ftp"
            },
            "geo": {
                "protocol": "geo",
                "caption": "geo"
            },
            "localfiles": {
                "show": false,
                "collection": [
                    {
                        "path": "upload",
                        "name": "localfiles"
                    }
                ]
            }
        }
    },
    "airflowSettings": {
        "core__executor": "LocalExecutor",
        "core__parallelism": 1,
        "core__dag_concurrency": 1,
        "core__max_active_runs_per_dag": 1,
        "core__hostname_callable": "socket.gethostname"
    },
    "aria2cSettings": {
        "--console-log-level": "debug",
        "--remove-control-file": true,
        "--allow-overwrite": true,
        "--auto-file-renaming": false
    },
    "databaseSettings":{
        "db_port": 5432,
        "db_user": "airflow",
        "db_password": "airflow",
        "db_name": "airflow"
    },
    "devel":{
        "simulation": false,
        "mac_update_from_devel": false
    }
}
```

### CODE REVIEW

**Comment by heylel-b-sh** [comment]
Think where do we use `baseUrl` from settings.

**Comment by heylel-b-sh** [comment]
Do not forget to remove unused `scidapSSLPort`, `sslCert` and `sslKey` from the UI. Use checkbox for `enableSSL`

**Comment by heylel-b-sh** [comment]
Think if we need to skip `settings.loadedFrom` when saving to `config.json` as this field is more like technical information from where settings where loaded and not something that used may update.

**Comment by heylel-b-sh** [comment]
For macOS bundle if you manually update `databaseSettings` from the`config.json`, airflow won't be able to connect to it unless you downgrade `latestUpdateVersion` to run initial configuration to make correspondent changes in `airflow.cfg`

**Comment by heylel-b-sh** [comment]
Set `airflowSettings` in `getAirflowEnvVar ` so we don't need to patch `airflow.cfg`

**Comment by heylel-b-sh** [comment]
Consider skipping running `airflow` from `waitForInitConfiguration` if we don't need to patch `airflow.cfg`

**Comment by heylel-b-sh** [comment]
Do not forget to update `rcServer ` before merging this pull request.

**Comment by heylel-b-sh** [comment]
Bug in NJS-Client. `systemRoot` should end with `/`

**Comment by heylel-b-sh** [comment]
We moved all certificate related logic from the satellite to the main server.

**Comment by heylel-b-sh** [comment]
Doesn't work without `NODE_ENV: 'development'`

**Comment by heylel-b-sh** [comment]
Error when building webui-aria2 caused by deprecated packages that it uses. Few of them are node-pre-gyp and node-sass. It looks like they don't work on Node 12.x.x. When building with node 10.17.0, for example, I don't see any errors.

**Comment by heylel-b-sh** [comment]
It doesn't look like `baseUrl` settings needed for Ubuntu setting. It's only used by App in UI.

**Comment by heylel-b-sh** [comment]
**DONE**
In the default setting set `core__max_active_runs_per_dag` to at least 3, `core__parallelism` and `core__dag_concurrency ` may remain the same. The reason is to prevent Airflow from getting stuck when somehow DagRun is not marked as finished. Having more than 1 `max_active_runs_per_dag` will allow to restart the sample from the UI, wait untill its time in a queue comes, and then it will be restarted.

**Comment by heylel-b-sh** [comment]
**DONE**
Double check with Daniel what was actually implemented for accessing local files on the satellite. We have deprecated settings `localFiles` that is not currently used by NJS-Client. Also, as a temporary solution (hardcoded on one of the satellites) this section was added to the `remotes`
```
"localfiles": {
    "show": true,
    "collection": [
             {
                     "path": "/home/scidap/scidap/uploads",
                     "name": "localfiles"
             }
    ]
}
``` 
However, the `show` field is used in exactly the same way we used `localFiles` before. So only one of them should remain. Also, perhaps, the word `collection` here came from BioWardbobe-NG

**Comment by heylel-b-sh** [comment]
NJS-Client need to have few minor bugs fixed and then updated to the latest. Otherwise, it won't work.
- **DONE** Merge this pull request https://bitbucket.org/datirium/scidapsatelliteinteractions/pull-requests/91
- Solve this bug https://datirium.atlassian.net/jira/software/projects/SDAP/boards/2?selectedIssue=SDAP-566

**DONE** macOS building scripts are not changed and not checked.

**Comment by heylel-b-sh** [comment]
There is no way to configure path to the folder available from SciDAP using Electron UI. Additionally, the checkbox to turn On/Off this feature doesn't work (so it's Off by default). The location of the parameter to control this feature was changed in the settings file (now it's `remotes.localfiles.show`).

**Comment by heylel-b-sh** [comment]
Check it this helps to fix invalid range problem.
Possible solution `--always-resume=false` because
```
--always-resume [true|false]
Always resume download. If true is given, aria2 always tries to resume download and if resume is not possible, aborts download. If false is given, when all given URIs do not support resume or aria2 encounters N URIs which does not support resume (N is the value specified using --max-resume-failure-tries option), aria2 downloads file from scratch. See --max-resume-failure-tries option. Default: true
```
A problem
```
10/04 11:32:36 [INFO] CUID#2348 - Response received:
HTTP/1.1 200 OK
Last-Modified: Mon, 27 Sep 2021 01:24:30 GMT
Content-Length: 3361513137
Content-Type: application/x-gzip
Connection: close
Date: Mon, 04 Oct 2021 15:33:51 GMT

10/04 11:32:36 [ERROR] CUID#2348 - Download aborted. URI=ftp://XXXX:YYYY@usftp21.novogene.com:21/raw_data/ABBW244/ABBW244_CKDL210019155-1a-AK5302-AK3490_HKGC7DSX2_L1_2.fq.gz
Exception: [AbstractCommand.cc:351] errorCode=8 URI=ftp://XXXX:YYYY@usftp21.novogene.com:21/raw_data/ABBW244/ABBW244_CKDL210019155-1a-AK5302-AK3490_HKGC7DSX2_L1_2.fq.gz
  -> [HttpResponse.cc:86] errorCode=8 Invalid range header. Request: 501850408-0/3361513137, Response: 0-3361513136/3361513137
```

**Review by portah — APPROVED** [review]

**Pull request merged**
